"""
Meta-Solver Core Framework

A generic self-improving optimization system that uses LLMs to generate ideas
and rigorous testing to validate improvements.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Callable, Optional
from enum import Enum
import time
import json
import hashlib


class Difficulty(Enum):
    EASY = "easy"
    MEDIUM = "medium"
    HARD = "hard"


@dataclass
class TestCase:
    """A single test case for evaluation."""
    id: str
    data: Any
    difficulty: Difficulty
    expected: Optional[Any] = None  # For problems with known answers
    metadata: dict = field(default_factory=dict)


@dataclass 
class EvalResult:
    """Result of evaluating a solution on a test case."""
    test_case_id: str
    score: float  # Higher is better, normalized 0-1 if possible
    time_taken: float  # Seconds
    success: bool
    details: dict = field(default_factory=dict)
    

@dataclass
class Idea:
    """An idea generated by an LLM."""
    id: str
    source_llm: str
    raw_text: str
    extracted_approach: str
    confidence: float  # Self-reported or parsed confidence
    timestamp: float = field(default_factory=time.time)
    
    @staticmethod
    def generate_id(text: str, source: str) -> str:
        return hashlib.md5(f"{source}:{text[:200]}".encode()).hexdigest()[:12]


@dataclass
class Attempt:
    """Record of an attempt to implement and test an idea."""
    idea_id: str
    implementation: Any  # Could be code, parameters, etc.
    results: list[EvalResult]
    aggregate_score: float
    improvement_over_baseline: float
    accepted: bool
    rejection_reason: Optional[str] = None
    timestamp: float = field(default_factory=time.time)


class Problem(ABC):
    """Abstract interface for defining a problem."""
    
    @abstractmethod
    def describe(self) -> str:
        """Return a clear description of the problem for LLMs."""
        pass
    
    @abstractmethod
    def describe_current_approach(self) -> str:
        """Describe the current best approach/solution."""
        pass
    
    @abstractmethod
    def get_test_cases(self, difficulty: Difficulty) -> list[TestCase]:
        """Return test cases at the specified difficulty level."""
        pass
    
    @abstractmethod
    def evaluate(self, solution: Any, test_case: TestCase) -> EvalResult:
        """Evaluate a solution on a single test case."""
        pass
    
    def format_failure_examples(self, failures: list[tuple[TestCase, EvalResult]], max_examples: int = 3) -> str:
        """Format failure cases for the LLM prompt. Override for custom formatting."""
        if not failures:
            return "No notable failures yet."
        
        lines = []
        for tc, result in failures[:max_examples]:
            lines.append(f"- Case {tc.id} ({tc.difficulty.value}): Score {result.score:.2f}")
            if result.details:
                lines.append(f"  Details: {result.details}")
        return "\n".join(lines)


class Solution(ABC):
    """Abstract interface for a solution that can be modified by ideas."""
    
    @abstractmethod
    def clone(self) -> 'Solution':
        """Create a copy of this solution for modification."""
        pass
    
    @abstractmethod
    def apply_modification(self, modification: dict) -> bool:
        """Apply a modification (from an idea). Returns success."""
        pass
    
    @abstractmethod
    def execute(self, test_case: TestCase) -> Any:
        """Run the solution on a test case."""
        pass
    
    @abstractmethod
    def serialize(self) -> str:
        """Serialize for storage/comparison."""
        pass


class LLMInterface(ABC):
    """Abstract interface for LLM providers."""
    
    @property
    @abstractmethod
    def name(self) -> str:
        pass
    
    @abstractmethod
    def generate(self, prompt: str, temperature: float = 0.7) -> str:
        """Generate a response to the prompt."""
        pass
    
    @abstractmethod
    def critique(self, idea: str, problem_context: str) -> tuple[float, str]:
        """Critique an idea. Returns (score 0-1, reasoning)."""
        pass


@dataclass
class History:
    """Tracks all attempts and their outcomes."""
    attempts: list[Attempt] = field(default_factory=list)
    ideas_seen: set = field(default_factory=set)
    best_score: float = 0.0
    best_solution_id: Optional[str] = None
    
    def add_attempt(self, attempt: Attempt):
        self.attempts.append(attempt)
        self.ideas_seen.add(attempt.idea_id)
        if attempt.accepted and attempt.aggregate_score > self.best_score:
            self.best_score = attempt.aggregate_score
    
    def get_recent_failures(self, n: int = 5) -> list[Attempt]:
        """Get recent failed attempts for context."""
        failures = [a for a in self.attempts if not a.accepted]
        return failures[-n:]
    
    def get_successful_patterns(self) -> list[str]:
        """Extract patterns from successful attempts."""
        return [a.idea_id for a in self.attempts if a.accepted]
    
    def to_json(self) -> str:
        """Serialize history for storage."""
        return json.dumps({
            'attempts': len(self.attempts),
            'accepted': len([a for a in self.attempts if a.accepted]),
            'best_score': self.best_score,
            'ideas_tried': len(self.ideas_seen)
        }, indent=2)


class Comparator:
    """Compares solutions to determine if there's real improvement."""
    
    def __init__(self, 
                 min_improvement: float = 0.01,  # 1% minimum improvement
                 regression_tolerance: float = 0.005,  # 0.5% regression tolerance
                 require_no_regression: bool = True):
        self.min_improvement = min_improvement
        self.regression_tolerance = regression_tolerance
        self.require_no_regression = require_no_regression
    
    def compare(self, 
                baseline_results: list[EvalResult], 
                candidate_results: list[EvalResult]) -> tuple[bool, str, float]:
        """
        Compare baseline vs candidate results.
        Returns (should_accept, reason, improvement_delta)
        """
        if len(baseline_results) != len(candidate_results):
            return False, "Mismatched result counts", 0.0
        
        baseline_avg = sum(r.score for r in baseline_results) / len(baseline_results)
        candidate_avg = sum(r.score for r in candidate_results) / len(candidate_results)
        
        improvement = candidate_avg - baseline_avg
        
        # Check for regressions on individual cases
        if self.require_no_regression:
            regressions = []
            for b, c in zip(baseline_results, candidate_results):
                if c.score < b.score - self.regression_tolerance:
                    regressions.append(b.test_case_id)
            
            if regressions:
                return False, f"Regression on cases: {regressions}", improvement
        
        # Check minimum improvement threshold
        if improvement < self.min_improvement:
            return False, f"Improvement {improvement:.4f} below threshold {self.min_improvement}", improvement
        
        return True, f"Accepted: {improvement:.4f} improvement", improvement


class PromptBuilder:
    """Builds prompts for the LLM ensemble."""
    
    IDEA_GENERATION_TEMPLATE = """
# Problem Description

{problem_description}

# Current Approach

{current_approach}

# Recent Failures/Challenges

{failure_examples}

# What We've Already Tried

{tried_approaches}

# Your Task

Think broadly and creatively about this problem. Consider:
- Are there any mathematical properties we're not exploiting?
- Could a different algorithm family work better?
- Are there heuristics from related problems?
- Is there a way to decompose this problem differently?
- What preprocessing or problem transformation might help?

Please propose 1-3 concrete ideas, each with:
1. **Idea Name**: Brief descriptive name
2. **Core Insight**: What observation motivates this?
3. **Approach**: How would you implement it?
4. **Expected Benefit**: Why might this help?
5. **Potential Risks**: What could go wrong?
6. **Confidence**: Your confidence level (low/medium/high)

Focus on ideas that are DIFFERENT from what's been tried.
"""

    CRITIQUE_TEMPLATE = """
# Problem Context

{problem_description}

# Proposed Idea

{idea_text}

# Evaluation Request

Please critically evaluate this idea:
1. Is the core insight valid?
2. Are there obvious flaws or edge cases?
3. How likely is this to produce meaningful improvement?
4. Is this idea sufficiently different from standard approaches?

Rate the idea from 0.0 to 1.0 and explain your reasoning.
Format your response as:
SCORE: [0.0-1.0]
REASONING: [your analysis]
"""

    @classmethod
    def build_idea_prompt(cls, 
                          problem: Problem, 
                          history: History,
                          max_failure_examples: int = 5) -> str:
        """Build the main idea generation prompt."""
        
        # Get failure examples
        recent_failures = history.get_recent_failures(max_failure_examples)
        failure_text = "\n".join([
            f"- Attempt {a.idea_id}: {a.rejection_reason or 'No specific reason'}"
            for a in recent_failures
        ]) if recent_failures else "No notable failures yet."
        
        # Get tried approaches  
        tried = history.get_successful_patterns()
        tried_text = "\n".join([f"- {t}" for t in tried[-10:]]) if tried else "Starting fresh."
        
        return cls.IDEA_GENERATION_TEMPLATE.format(
            problem_description=problem.describe(),
            current_approach=problem.describe_current_approach(),
            failure_examples=failure_text,
            tried_approaches=tried_text
        )
    
    @classmethod
    def build_critique_prompt(cls, problem: Problem, idea_text: str) -> str:
        """Build a critique prompt for pre-filtering ideas."""
        return cls.CRITIQUE_TEMPLATE.format(
            problem_description=problem.describe(),
            idea_text=idea_text
        )
